### ISSUE TITLE
[bug] email validation

### ISSUE THREAD

**Issue by rivenbryan** [rivenbryan/sc2006#14]
![image](https://user-images.githubusercontent.com/9747097/221392159-e9714e6e-fd3b-4201-a74f-b948f49a0297.png)

If user tries to forget password and key in a NON email details, it crashes the server. Pls fix

**Comment by AloysiusTan** [comment]
Done. Will perform the check to see if it match the email domain
![image](https://user-images.githubusercontent.com/97999822/221409124-ca5675c6-b456-4bba-be72-011ac6356b00.png)

**Comment by AloysiusTan** [comment]
![image](https://user-images.githubusercontent.com/97999822/221409775-d986882a-2ae9-4bdd-90cb-30dea15a97f4.png)
